name: 'Execução manual N1'

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Testes E2E (end-to-end)
        run: yarn run e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: cypress/reports/html/
  
  e2e-tests-Windows-Chrome:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes-windows-chrome
          path: cypress/reports/html/

          
