# CI de nível 01 - Disparo manual a partir de 1 clique

# nome que vai aparecer nas opções de pipe
name: 'Execução manual N1'

# triggers ou gatilhos de execução (regras de disparo)
# gatilho de exec manual = workflow-dispatch

on:
  workflow_dispatch:

jobs:
  # descrição do job
  e2e-tests:
    # maquina que o job vai executar
    runs-on: 'ubuntu-latest'
    timeout-minutes: 60

    # passo a passo das ações do job
    steps:
      # clone
      - uses: actions/checkout@v4

      # se precisar testar em uma versão específica do node:
      #- uses: actions/setup-node@v4
      #   with:
      #     node-version: lts/*

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando Cypress
        run: yarn cypress install

      - name: Testes E2E (end-to-end)
        run: yarn run e2e

      # passed, failed, cancelled
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }} # expressão do ghActions
        with:
          name: relatorio-de-testes
          path: ./reports
